Stability updates + layout
pepkit/pephub pull request #139
Opened 2023-04-20 19:15 UTC by nleroy917

This includes a lot of stability improvements after the transition to React. Thanks for pointing out these things @Khoroshevskyi 

Improvements include:
1. Change key-binding on global search
2. Drag n drop was broken
3. Files were not getting uploaded properly for project submission
4. Sample table editing was broken due to trailing commas
5. New project page layout
6. Some new components + CSS utility classes to make development easier
7. Sort project list by default to most recent first in the list

2023-04-22 18:42 UTC, Khoroshevskyi requested changes
There is few things that still have to be polished: 
1) Download zip 3 different places. I think this link (or downloading button) should be in one place. E.g under "Get project" drop button. 
2) We don't have https downloading link (only zip) so I wouldn't add it to our UI now.
![image](https://user-images.githubusercontent.com/41573628/233801021-47f5b219-1508-4aba-baee-fe0860300d66.png)

3) PEP version shows incorrect version:
![image](https://user-images.githubusercontent.com/41573628/233800999-5aeca348-1abb-4539-b97c-61304ba8996a.png)

4) Add subtables to UI. In my opinion everything is ready for adding subsamples. + I just added functionality for updating subsample tables. So it shouldn't be big problem.

Everything else looks good:)

2023-04-22 18:42 UTC, Khoroshevskyi commented on pephub/routers/api/v1/namespace.py
> +    # sort by last_update_date
1) if action in next line is explicit, we shouldn't add any comments. I think sorting function is understandable:)
2) This functionality should be in pepdbagent, not here. I wiil create Issue on this topic.

2023-04-28 12:15 UTC, nleroy917 commented
Would be ideal to address these issues prior to merge + release:
- #143 
- #142 
- #141 
- #140 
- #131

2023-04-28 19:51 UTC, nleroy917 commented
@Khoroshevskyi Changes should be nearly complete now if you wanted to test it out.

2023-04-28 21:07 UTC, merged